version: "3"

services:
  server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    environment:
      - APP_MODE=SERVER
      - MONGO_DBNAME=microblog
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis:6379
      - SERVER_PORT=8000
    command: sh -c "./wait-for-it.sh redis:6379 --strict --timeout=30 -- echo 'Redis is up' && ./wait-for-it.sh mongo:27017 --strict --timeout=30 -- echo 'MongoDB is up' && ./server"

  worker:
    build: .
    depends_on:
      - redis
      - mongo
    environment:
      - APP_MODE=WORKER
      - MONGO_DBNAME=microblog
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis:6379
    command: sh -c "./wait-for-it.sh redis:6379 --strict --timeout=30 -- echo 'Redis is up' && ./wait-for-it.sh mongo:27017 --strict --timeout=30 -- echo 'MongoDB is up' && ./server"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
